language: csharp
solution: csharp-rest-client.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2
env:
  - VERSION=1.6.1.$TRAVIS_BUILD_NUMBER
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script:
        - echo $VERSION
        - cd Tests/UnitTests/MessageBirdUnitTests
        - dotnet restore
        - dotnet test
        - cd ../../../MessageBird
        - dotnet restore
        - dotnet build
        - dotnet pack -p:PackageID=MessageBirdStaging -c Release -p:PackageVersion=$VERSION
    - stage: deploy
      script:
        - cd MessageBird
        - dotnet restore
        - dotnet build
        - dotnet pack -p:PackageID=MessageBirdStaging -c Release -p:PackageVersion=$VERSION
        - dotnet nuget push MessageBirdStaging.{VERSION}.nupkg -k $STAGING_KEY -s https://apiint.nugettest.org/v3/index.json
        